### ISSUE TITLE
Amazing addon, but it couldn't find qdbus I have installed.

### ISSUE THREAD

**Issue by pallaswept** [luisbocanegra/plasma-panel-spacer-extended#10]
I found this just now when looking for a spacer - not being aware that there's one built in - and I'm really glad I didn't know, because this is awesome!!
As I was configuring it before I used it I was getting really excited, this thing looks so amazing. I love a minimal and uncluttered interface and you can't get more minimal than empty space. Gee, I hope it's going to be available for qt6.... looks at github out of curiosity.... Already done a month ago! YES! I love it!

But then it didn't do anything at all. I noticed in the readme that it said it uses qdbus, so I thought, I'll see what happens if I run that from the CLI.... annnnnd I don't have it installed. OK that explains a lot :rofl: ... So I went to install it and it turns out I _do_ have it installed. But it wasn't in my path, it was at `/usr/lib64/qt5/bin/qdbus`. This is just where openSUSE puts it. I symlinked it to /usr/bin, and now it appears to be behaving. There was already a symlink there to the same binary, called `qdbus-qt5`.

I'm not sure if it's intended to expect it in the path or not, or if it tries to look for the qdbus-qt5 name in the path, I'm assuming not and I've found a corner-case. I did see the troubleshooting option there and ticked it but I've no idea where it's saving that log, or I'd provide it for you right away.

The symlink I made is a fine workaround, but it would be cool if I didn't need it. I'm not sure if this is a bug or a feature request, I'll leave that up to you.

Great widget anyway, thanks!!

**Comment by luisbocanegra** [comment]
Hi, thank you for the kind words, I am glad someone finds it useful :)

> As I was configuring it before I used it I was getting really excited, this thing looks so amazing. I love a minimal and uncluttered interface and you can't get more minimal than empty space. 

Yeah no space wasted :)

> I'm not sure if it's intended to expect it in the path or not, or if it tries to look for the qdbus-qt5 name in the path, I'm assuming not and I've found a corner-case.

It expects it to be in the path as `qdbus`, so yeah, it's hardcoded. I think an option to change the executable name would be better than adding all corner-cases 😆.

> I did see the troubleshooting option there and ticked it but I've no idea where it's saving that log, or I'd provide it for you right away.

Plasmoid logs _should_ appear in the output of `journalctl -f`, but don't remember if it's like that by default or something I enabled long ago.

**Comment by pallaswept** [comment]
It's better than useful - I just wanted a spot to rest my mouse off-screen when I'm watching a video or whatever, and not only did I get that, but I also got to remove my window buttons and gain a chunk of screen real estate when I thought I was giving some up. Love it!

An option to set the executable would be perfect. You can keep this issue open to track it if you want, or go ahead and close it since I do have a workaround I'm not stressed. Whatever works for you. Thanks again for the great widget.

BTW I had this feeling your name looked familiar, you're that guy who was in the window buttons for plasma 6 thread. I guess you might have made that widget redundant for me with this one hahaha but keep up the great work mate.

**Comment by luisbocanegra** [comment]
Custom qdbus command name is now on main (plasma 6)

**Comment by pallaswept** [comment]
Awesome! Thanks mate!!
