### ISSUE TITLE
Make it work out of the box

### ISSUE THREAD

**Issue by Joey2004-B** [luisbocanegra/plasma-panel-spacer-extended#11]
When I installed this widget, I got this error.
![Widget Error](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/150854563/2225ab5a-c0d5-4954-a2af-b9e8972d90bf)
Can you do something to fix it? Make it work better?

**Comment by Joey2004-B** [comment]
I think there's something missing in the instructions.

**Comment by luisbocanegra** [comment]
Looks like you didn't install the latest version of the plasmoid, try uninstalling it and make sure you pick the latest (1.4.0) when installing.

**Comment by Joey2004-B** [comment]
OK. I'll do it

God bless, and love you lots,
Joey ☦️❤️🧡💛💚🩵💙💜🩷

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Joey2004-B** [comment]
> Looks like you didn't install the latest version of the plasmoid, try uninstalling it and make sure you pick the latest (1.4.0) when installing. ![Screenshot_20240120_114849](https://private-user-images.githubusercontent.com/15076387/298298886-ce606f10-8f57-47de-9f68-e3603584bb39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzQwOTcsIm5iZiI6MTcwNTc3Mzc5NywicGF0aCI6Ii8xNTA3NjM4Ny8yOTgyOTg4ODYtY2U2MDZmMTAtOGY1Ny00N2RlLTlmNjgtZTM2MDM1ODRiYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE4MDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNzZkNTdhYmY3ZTJjYTJiNGRjYzQwZDc2ZjE4MGJjYWMyMGJjYzAzYWEyZDFkOTBmMGQ1MDBjYzBmYjk4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.StrEI33fTP7xNZz5sDoF9bm7k7fs4nwgDEjSAlF_Eog)

When I clicked on the install button, I wasn't given a menu like the one you shown me. I did install the latest version of it.

**Comment by luisbocanegra** [comment]
> > Looks like you didn't install the latest version of the plasmoid, try uninstalling it and make sure you pick the latest (1.4.0) when installing. ![Screenshot_20240120_114849](https://private-user-images.githubusercontent.com/15076387/298298886-ce606f10-8f57-47de-9f68-e3603584bb39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzQwOTcsIm5iZiI6MTcwNTc3Mzc5NywicGF0aCI6Ii8xNTA3NjM4Ny8yOTgyOTg4ODYtY2U2MDZmMTAtOGY1Ny00N2RlLTlmNjgtZTM2MDM1ODRiYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE4MDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNzZkNTdhYmY3ZTJjYTJiNGRjYzQwZDc2ZjE4MGJjYWMyMGJjYzAzYWEyZDFkOTBmMGQ1MDBjYzBmYjk4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.StrEI33fTP7xNZz5sDoF9bm7k7fs4nwgDEjSAlF_Eog)
> 
> When I clicked on the install button, I wasn't given a menu like the one you shown me. I did install the latest version of it.

That sounds like a bug in the Download new stuff thing?

- Which distro and plasma version are you using? 
- Also which version of the plasmoid is being installed? You can check the widget version from the widget settings in the about section or with this command `grep "Version" ~/.local/share/plasma/plasmoids/luisbocanegra.panelspacer.extended/metadata.json`

**Comment by Joey2004-B** [comment]
The distribution I used is Kubuntu (Actually Ubuntu)
The plasma version, I guess is 5.

Also, I installed a widget, not sure if it's yours, but I ended up having the titlebars of the windows disappear whenever I maximized them. That continued after I deleted the widget. I had to delete my user account and make a new one. Does your widget do that?

God bless, and love you lots,
Joey ☦️❤️🧡💛💚🩵💙💜🩷

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by luisbocanegra** [comment]
> The distribution I used is Kubuntu (Actually Ubuntu) The plasma version, I guess is 5. 

Please share the exact versions from System Settings > About this system

Alternatively, you could install the .plasmoid file from the releases (`plasmapkg2 -u PATH_TO_PLASMOID_FILE`) or clone/download this repository (5.27.6 branch is for plasma 5) and run the install script.

> Also, I installed a widget, not sure if it's yours, but I ended up having the titlebars of the windows disappear whenever I maximized them. That continued after I deleted the widget. I had to delete my user account and make a new one. Does your widget do that? God bless, and love you lots, Joey ☦️❤️🧡💛💚🩵💙💜🩷 Sent with [Proton Mail]([proton.me](https://proton.me/)) secure email.

No, this widget doesn't do that, you most likely installed this one https://github.com/psifidotos/applet-window-buttons or some other addon that uses that feature. Also you can revert that behavior with `kwriteconfig5 --file kwinrc --group Windows --key BorderlessMaximizedWindows --type bool false && qdbus org.kde.KWin /KWin reconfigure` no need to create new user :)

**Comment by Joey2004-B** [comment]
Thanks for telling me about that, bud! I'll take a screenshot of that comment!

As for the system information, I'm gonna answer that with a screenshot.
![My System](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/150854563/90c98302-9d1d-41dd-b6a6-30dad359ebcb)
I know you've got this! 👍🏻

**Comment by Joey2004-B** [comment]
Guess what? I got the thing with the titlebars disappearing again. I tried the command that you showed me, but it didn't work.

I didn't install any widgets this time. This time, it was a theme I've created after installing the widget that made the titlebars disappear when maximized.

**Comment by luisbocanegra** [comment]
>Guess what? I got the thing with the titlebars disappearing again. I tried the command that you showed me, but it didn't work.
> 
> I didn't install any widgets this time. This time, it was a theme I've created after installing the widget that made the titlebars disappear when maximized.

The command works for me but I am on wayland, try logging out and in. 

You need to figure out what is causing that, look for `BorderlessMaximizedWindows=true` in `~/.config/kwinrc` if is not there it may be something else, if you use Latte Dock, I think it can do that too, also if you use a small top bar make sure it isn't in "Windows go below mode".

BTW, did the widget work after installing manually?

**Comment by Joey2004-B** [comment]
I use X11. I have a top bar. I checked that it's set to "Always Visible." 💡 You gave me an idea! I'll use the `grep` command to search for the `BorderlessMaximizedWindows=true` thing from my home directory! If not, I'll try this command in Wayland. Thanks for helping me with this issue as well as the issue with your widget. Let me know if it's fixed. 👍🏻

**Comment by Joey2004-B** [comment]
I tried the `grep` command, but it's dragging its feet. 🐌  I also tried searching for it in the file explorer, no such luck. I'm going Wayland.

**Comment by Joey2004-B** [comment]
I tried the `grep` command, but it's dragging its feet. 🐌  I also tried searching for it in the file explorer, no such luck. I'm using wayland

**Comment by Joey2004-B** [comment]
I tried the command in Wayland, but I got this error message: `Service 'org.kde.kwin' does not exist.` Still, the windows' title bars hide when I maximize them. I've got another idea! 💡  Maybe I should search for `BorderlessMaximizedWindows=true` from the root directory!

**Comment by Joey2004-B** [comment]
I searched for `BorderlessMaximizedWindows=true` in the file explorer. It's dragging its feet. Let me know if you've got more ideas.

**Comment by Joey2004-B** [comment]
OK, I have no such luck looking for `BorderlessMaximizedWindows=true`. I think the problem is with a global theme or Plasma widget I have installed. I'm gonna be signed into a test account.

**Comment by Joey2004-B** [comment]
Guess what? I was going through my installed widgets, and I discovered that I didn't uninstall the Window Buttons widget. 😮  I'll continue going through the widgets and see if there are any widgets that cause the title bars to disappear when minimized.

**Comment by Joey2004-B** [comment]
P.S. I found another widget you made. It's the KDE material YOu colors. Could you give me the URL to its repo? It wasn't working right, and the instructions don't work on my system.

**Comment by luisbocanegra** [comment]
> If not, I'll try this command in Wayland. Thanks for helping me with this issue as well as the issue with your widget. Let me know if it's fixed. 👍🏻

I will check in a kubuntu vm, maybe is a distro issue as I have tried with others (Neon, Fedora, Arch) and worked fine there.

**Comment by luisbocanegra** [comment]
> P.S. I found another widget you made. It's the KDE material YOu colors. Could you give me the URL to its repo? It wasn't working right, and the instructions don't work on my system.

https://github.com/luisbocanegra/kde-material-you-colors/ btw all my widgets have the url to the repos in widget settings > about and also in the kde store as homepage ;)

**Comment by Joey2004-B** [comment]
OK! Thanks for the tip! 👍🏻

**Comment by Joey2004-B** [comment]
I found the culprit to my maximized windows issue! There was a little something in this text file:
![Defaults file](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/150854563/eb6bffc3-7fbc-44c4-b31d-648b34c1b928)
This is a picture of the edited version of it and I was able to revert it without deleting my account 😄

**Comment by luisbocanegra** [comment]
> Thanks for trying to help me! I appreciate that!

You're welcome!

Back to your main issue:

I tried installing the widget on Kubuntu vm and it listed all the versions, so this looks like a very isolated bug that you are having, I can only give you some suggestions:

- Try other widgets that have multiple versions e.g. "Intel GPU Monitor" (also made by me)
- If other widgets have the same problem try updating your plasma version by updating your system.
- If after updating to newer plasma version the issue still occurs you may want to try in a new user, if it doesn't occur there it may be that some cache file from the addons thing got corrupted. 

Whether it occurs in a new user or not (and you can still reproduce it), then consider opening a bug report in your distro or kde issue tracker as this is something I cannot fix.

**Comment by Joey2004-B** [comment]
I'll try to get your "Intel GPU Monitor" widget. I don't know how to upgrade my Plasma version. I do have a "guinea-pig" user that I can test your widget on.

**Comment by Joey2004-B** [comment]
I got your Intel GPU Monitor to work. 👍🏻

**Comment by luisbocanegra** [comment]
> I'll try to get your "Intel GPU Monitor" widget. I don't know how to upgrade my Plasma version.

That's usually done by upgrading your system packages, you get newer versions if kubuntu provides them in the repositories, if not then is fine.

> I got your Intel GPU Monitor to work. 👍🏻

But did it allow you to pick a version before installing? If not, you need to follow the steps in https://github.com/luisbocanegra/plasma-panel-spacer-extended/issues/11#issuecomment-1907640241

**Comment by Joey2004-B** [comment]
I didn't get to try your widget on my test account. I tried it on mine (after installing updates), I tried to follow along with the commands you have on your manual install section. Which directory should I run the `cmake` command mentioned?

**Comment by Joey2004-B** [comment]
I tried your widget on a test account on my machine. After updates, too! It didn't work. 😞

**Comment by luisbocanegra** [comment]
> I didn't get to try your widget on my test account. I tried it on mine (after installing updates), I tried to follow along with the commands you have on your manual install section. Which directory should I run the `cmake` command mentioned?

cmake and others are just packages you need to install then you run `./install.sh` inside the cloned/downloaded widget folder, if you go this way, you should also make sure to download the 5.27.6 branch which is for plasma 5.x, or just use the .plasmoid file from releases and install as I mentioned earlier.

> I tried your widget on a test account on my machine. After updates, too! It didn't work. 😞

Try reporting this bug to your distro or kde bug tracker, they should be able you help figure out where the problem with the kde "get new stuff" is.

**Comment by Joey2004-B** [comment]
I have a couple questions about your Kubuntu VM that you used. What version of the operating system is it? Did you install any packages to get the widget to work?

The error message I'm getting is saying something about something being missing, so I guess the way to tackle this issue is to install the missing piece.

**Comment by luisbocanegra** [comment]
> I have a couple questions about your Kubuntu VM that you used. What version of the operating system is it? Did you install any packages to get the widget to work?

It was the version 23.10, no I didn't need to install any package

> The error message I'm getting is saying something about something being missing, so I guess the way to tackle this issue is to install the missing piece.

Not really, since that missing piece was needed only for a previous version, the latest one (1.4.0) doesn't need that. The problem here is that your system is not letting you pick the version when installing widgets, if it did you would have picked the latest one and not have missing qt plugin error at all.

Try to install the widget in the kubuntu VM and let me know if it lets you choose a version when installing the widget there.

**Comment by Joey2004-B** [comment]
Guess what? I'm seeing something different in your widget's page in Discovery on my side! There is a button that opens a drop-down menu labeled `sources`. There are 3 entries for version 1.4.0. I'll try them all and see if any of them works. Thanks for helping me out!

**Comment by Joey2004-B** [comment]
I tried the first entry from the sources list, same result as the first time I installed the widget. When I tried the second one, Discover is taking a long time, and I don't know how to stop it. I tried the cancel button, but whenever I close Discover, a notification appears saying that Discover is working on it. How can I get it to stop?

**Comment by luisbocanegra** [comment]
> I tried the first entry from the sources list, same result as the first time I installed the widget. When I tried the second one, Discover is taking a long time, and I don't know how to stop it. I tried the cancel button, but whenever I close Discover, a notification appears saying that Discover is working on it. How can I get it to stop?

Not sure maybe stopping it from the System monitor, can you show where this `sources` drop-down is, I don't use Discover and can't find that.

**Comment by Joey2004-B** [comment]
Dang, I was about to pull it up to take a screenshot, but the sources button wasn't there anymore. However, I do have an illustration.
![Where the buttons were](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/150854563/74632808-9f5a-4043-880b-c28997202b77)
What did you use to install your widget?

**Comment by luisbocanegra** [comment]
> Dang, I was about to pull it up to take a screenshot, but the sources button wasn't there anymore. However, I do have an illustration. ![Where the buttons were](https://private-user-images.githubusercontent.com/150854563/300133607-74632808-9f5a-4043-880b-c28997202b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMTE5NTYsIm5iZiI6MTcwNjMxMTY1NiwicGF0aCI6Ii8xNTA4NTQ1NjMvMzAwMTMzNjA3LTc0NjMyODA4LTlmNWEtNDA0My04ODBiLWMyODk5NzIwMmI3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQyMzI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjJmN2QxZmNhZWUwMmQyNTNmODk0MWQyZjgwMTIwYzhhYTAwZWUzYzM5MGQyNWY2OWJhMTY5MDBhYmUzNzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lVuYoVawFEF25oaf7ztLmUQKAfUGyOct_TUyMi0Wd6Q)

I see it now, tested with the Intel GPU Monitor widget and it shows three entries too for the latest version, picked the last one and it worked.

> What did you use to install your widget?
From the panel, Right click > Add Widgets > Get new widgets > Download New plasma widgets.

That's what I do to verify it will work for others since I usually just install using the `./install.sh` to test my changes faster.

**Comment by Joey2004-B** [comment]
I didn't try your approach. I also got my self some additional application launchers as well! 😄 I selected the latest version (1.4.0), but your widget didn't work. 😞

**Comment by luisbocanegra** [comment]
> I followed your instructions. I also got my self some additional application launchers as well! 😄 I selected the latest version (1.4.0), but your widget didn't work. 😞

What do you mean it didn't work, still the same error? What exactly did you try? 

It should work if you install it from the plasmoid file from here https://github.com/luisbocanegra/plasma-panel-spacer-extended/releases/tag/v1.4.0 with the instructions in https://github.com/luisbocanegra/plasma-panel-spacer-extended/issues/11#issuecomment-1902410257.

Also you didn't tell me if it worked from a VM or live USB, it did for me when I tried, so it must be something in your end that's not working as expected and installing in a clean environment will tell you if is something wrong in your current install or a problem with something else.

**Comment by luisbocanegra** [comment]
> I'm using Kubuntu as my OS instead of Windows. I didn't use live media or a VM.

I know, it was just to see if the problem was something out of your control and not a bug that something in your current setup was causing e.g. broken package or even some weird network problem.

> Guess what? I tried installing your widget the second time from the "Get new Widgets" section from the "Add Widgets" screen, and IT WORKED! 🥳 PRAISE THE LORD THAT IT WORKS!!!

Finally! It let you pick a version there, right?

**Comment by Joey2004-B** [comment]
Correct, I used the Add Widgets menu from Edit Mode.

Man, that widget is cool! It lets you manipulate windows without clicking on the windows' title bars! There is a window decoration theme that gets rid of the window buttons. It's called "Minimalist."

Thanks a bunch for helping me and creating this widget! I can make a simple-looking panel that can do a heck of a lot of things!

And the last thing I'm going to say here is thank you for helping me get it to work, and thanks for creating it! Have a wonderful day! 😄
