### ISSUE TITLE
kde plasma 6.1 dev

### ISSUE THREAD

**Issue by IF-tiger** [luisbocanegra/plasma-panel-spacer-extended#13]
```
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Plugin Id: luisbocanegra.panelspacer.extended
Version: 1.5.0
CMake Error at CMakeLists.txt:23 (find_package):
  By not providing "FindKF5Plasma.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Plasma", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Plasma" with
  any of the following names:

    KF5PlasmaConfig.cmake
    kf5plasma-config.cmake

  Add the installation prefix of "KF5Plasma" to CMAKE_PREFIX_PATH or set
  "KF5Plasma_DIR" to a directory containing one of the above files.  If
  "KF5Plasma" provides a separate development package or SDK, be sure it has
  been installed.

```

I tried to find this dependency through the repository to make sure I had the required dependency installed, but I still got an error，
thank you work

**Comment by luisbocanegra** [comment]
I was able to install with commit https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/19cc078f1cca49ef5f4c6df03a586455a0964b50 KF5Plasma changed to Just Plasma according to https://discuss.kde.org/t/cmake-complain-about-missing-kf6plasma/8675

**Comment by IT-Tagore** [comment]
> 我能够使用提交 [19cc078](https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/19cc078f1cca49ef5f4c6df03a586455a0964b50) 进行安装，KF5Plasma 根据 https://discuss.kde.org/t/cmake-complain-about-missing-kf6plasma/8675 更改为仅 Plasma

sorry Still not working
`find_package(Plasma 6.0.80 REQUIRED)` I tried to change it to this and it didn't work
ChatGPT says it could be an issue with the environment variables

**Comment by IT-Tagore** [comment]
Operating System: openSUSE Tumbleweed 20240207
KDE Plasma Version: 6.0.80
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.1
Kernel Version: 6.7.4-1-default (64-bit)
Graphics Platform: Wayland

my device info

**Comment by luisbocanegra** [comment]
We need to figure out which package provides Plasma (formerly KF5Plasma), alternatively you can run `kpackagetool6 --upgrade package` inside the cloned folder and that should work, or `plasmapkg2 -u plasmoid-spacer-extended-v1.5.0.plasmoid` one of that should work I guess?

**Comment by IT-Tagore** [comment]
successful， thanks, I'd like to ask what to do when the window is maximized, hiding the window title bar，Also, I think your cmakelist file needs to be checked for qt before installing
![屏幕截图_20240209_030638](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/60809013/a5b2e483-2743-40cd-9bce-07dba9d20037)
I don't know how to use cmake, I refer to the cmakelist file of other projects, and the miraculous compilation is done

**Comment by luisbocanegra** [comment]
> I'd like to ask what to do when the window is maximized, hiding the window title bar

Not sure I understand this. When a window is maximized titlebars are hidden if [applet-window-buttons6](https://github.com/moodyhunter/applet-window-buttons6) is installed, then to interact with them you use that widget and `plasma-panel-spacer-extended` to do more things like dragging them. 

If the titlebars don't hide for you then run `kwriteconfig5 --file kwinrc --group Windows --key BorderlessMaximizedWindows --type bool true && qdbus org.kde.KWin /KWin reconfigure` to enable that.

> Also, I think your cmakelist file needs to be checked for qt before installing
![屏幕截图_20240209_030638](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/60809013/a5b2e483-2743-40cd-9bce-07dba9d20037)

True, I'll add that later

> I don't know how to use cmake, I refer to the cmakelist file of other projects, and the miraculous compilation is done

Yeah, I barely know cmake was mostly guided by looking at other projects and intuition 😆

**Comment by IT-Tagore** [comment]
> > I'd like to ask what to do when the window is maximized, hiding the window title bar
> 
> Not sure I understand this. When a window is maximized titlebars are hidden if [applet-window-buttons6](https://github.com/moodyhunter/applet-window-buttons6) is installed, then to interact with them you use that widget and `plasma-panel-spacer-extended` to do more things like dragging them.
> 
> If the titlebars don't hide for you then run `kwriteconfig5 --file kwinrc --group Windows --key BorderlessMaximizedWindows --type bool true && qdbus org.kde.KWin /KWin reconfigure` to enable that.
> 
> > Also, I think your cmakelist file needs to be checked for qt before installing
> > ![屏幕截图_20240209_030638](https://private-user-images.githubusercontent.com/60809013/303576432-a5b2e483-2743-40cd-9bce-07dba9d20037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzgxODgsIm5iZiI6MTcwNzU3Nzg4OCwicGF0aCI6Ii82MDgwOTAxMy8zMDM1NzY0MzItYTViMmU0ODMtMjc0My00MGNkLTliY2UtMDdkYmE5ZDIwMDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE1MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1OGE1M2M4Y2I0ODJjNTI3ZGExMzQyZWJlZDM0YmI2ZTUzYjNmZDE1ZjA4Y2VhMjI1ODhiY2VlMjU2MzM0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uc8S0GNN2w_gavmHrxMkQPXwmCkDDro9bctgMKRMjV0)
> 
> True, I'll add that later
> 
> > I don't know how to use cmake, I refer to the cmakelist file of other projects, and the miraculous compilation is done
> 
> Yeah, I barely know cmake was mostly guided by looking at other projects and intuition 😆

thank you, happy new year
