### ISSUE TITLE
i cannot adjust manual size

### ISSUE THREAD

**Issue by Vilez0** [luisbocanegra/plasma-panel-spacer-extended#14]
simply i cannot adjust manual size for the spacer, there isnt any option here (plasmashell 5.93.0,arch linux)
when i remove the tick of set flexible size the widget is gone and cannot see it until enter edit mode

**Comment by luisbocanegra** [comment]
Option to change fixed width was added to appearance settings https://github.com/luisbocanegra/plasma-panel-spacer-extended/releases/tag/v1.5.1

**Comment by Vilez0** [comment]
> Option to change fixed width was added to appearance settings https://github.com/luisbocanegra/plasma-panel-spacer-extended/releases/tag/v1.5.1

I just had a chance to try this fix
I cannot set fixed length more than 99
