### ISSUE TITLE
Cannot set manual size for more than 99

### ISSUE THREAD

**Issue by Vilez0** [luisbocanegra/plasma-panel-spacer-extended#17]
cannot set the manual size for the plasmoid more than 99

**Comment by luisbocanegra** [comment]
My bad, an update that actually includes the fix will be released soon

**Comment by luisbocanegra** [comment]
Please update to the latest version and let me know if it works as expected now

**Comment by Vilez0** [comment]
> Please update to the latest version and let me know if it works as expected now

I'm sorry for the late reply. I tried it with the latest version and the problem seems to be solved
