### ISSUE TITLE
Enable Drag&Drop

### ISSUE THREAD

**Issue by PapierFliegr** [luisbocanegra/plasma-panel-spacer-extended#19]
Most user (at least I think so) are used to drag a window to get it to the desired position. 
Here when using the option to move a window by dragging on the panel, the dragging motion just enables the action and a mouseclick drops the window.

I think, a smoother action would be to drag, hold (after .. ms the window will move) and drop.
Or maybe even better: Start dragging and after moving a certain amout of pixels the window will move and drop.

**Comment by luisbocanegra** [comment]
Agree, don't remember the exact reason I did it like this, but it was probably to allow tracking the drag outside the panel. Will need to look more deeply into this.

**Comment by luisbocanegra** [comment]
@PapierFliegr drag & drop instead of drag and click to drop has been pushed to main in case you want to try it 🙂
Here's a quick demo

https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/15076387/e9039bcf-9a51-4de4-9697-cc97ed3b005f

**Comment by PapierFliegr** [comment]
Tried it right now... I love it!!!
Thank your very much :smile:
