### ISSUE TITLE
Dragging while the spacer geometry changes triggers wrong action

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-spacer-extended#23]
Initially reported in https://github.com/luisbocanegra/plasma-panel-spacer-extended/issues/22#issuecomment-2065802970

Dragging while the panel is shrinking/growing causes the dragging direction to be detected incorrectly, e.g. dragging down may be detected as dragging right.

**Steps to reproduce**
1. Have a widget that resizes dynamically such as Window Title, Global Menu, or Window Buttons
2. Try to initiate a drag down gesture while the spacer is growing/shrinking/moving
4. See wrong action (left or right) being executed instead of the intended one

**Comment by luisbocanegra** [comment]
Hi, @ShayBox can you install manually and check if this is fixed for you? After https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/f3724f9c6d2d05ffb6dbb986e2ce4964d516fb68 I can't seem to reproduce it anymore

**Comment by ShayBox** [comment]
Could you build a package? I can't get it to work, I'm probably missing a build dependency or something.

```
❯ ./package-plasmoid.sh
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Plugin Id: luisbocanegra.panelspacer.extended
Version: 1.6.0
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/shaybox/Downloads/plasma-panel-spacer-extended-main/build
[100%] Generating /home/shaybox/Downloads/plasma-panel-spacer-extended-main/plasmoid-spacer-extended-v1.6.0.plasmoid
no such file or directory
make[2]: *** [CMakeFiles/plasmoid.dir/build.make:72: CMakeFiles/plasmoid] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/plasmoid.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
It fails trying to `$ cmake --build build`

**Comment by luisbocanegra** [comment]
I think it couldn't find the zip command. Does `./install.sh` work?

or `kpackagetool6 -t Plasma/Applet -u package/`

or `kpackagetool6 -t Plasma/Applet -u plasmoid-spacer-extended-v1.6.1.zip` 

[plasmoid-spacer-extended-v1.6.1.zip](https://github.com/luisbocanegra/plasma-panel-spacer-extended/files/15108714/plasmoid-spacer-extended-v1.6.1.zip)

**Comment by ShayBox** [comment]
Ah yeah, I didn't have zip installed, thanks.

For some reason I wasn't able to install my built plasmoid, it just said error when trying to install, but yours worked fine, and they seem to have the same content, maybe the version has to be higher not the same as the currently installed one?

Anyway, the new version seems to fix the drag direction detection when the size changes from other widgets :+1:

**Comment by luisbocanegra** [comment]
> Ah yeah, I didn't have zip installed, thanks.
> 
> For some reason I wasn't able to install my built plasmoid, it just said error when trying to install, but yours worked fine, and they seem to have the same content, maybe the version has to be higher not the same as the currently installed one?

Maybe, specially if it was from the Add Widgets GUI

> Anyway, the new version seems to fix the drag direction detection when the size changes from other widgets 👍

Thanks!
