### ISSUE TITLE
Hand cursor (pointer) when hovering on panel

### ISSUE THREAD

**Issue by sibwaze** [luisbocanegra/plasma-panel-spacer-extended#24]
After updating plasmoid from 1.5 to 1.6, now i have wrong cursor while i am hovering on the panel plasmoid

**Comment by luisbocanegra** [comment]
Fixed in https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/87acb494b356c9a0819d5d658b13f7499c67c4cb

**Comment by sibwaze** [comment]
This issue is also fixed, thank you!
