### ISSUE TITLE
Middle click not working

### ISSUE THREAD

**Issue by sibwaze** [luisbocanegra/plasma-panel-spacer-extended#25]
Also after updating from 1.5.4 to 1.6, middle click action is not working anymore

**Comment by luisbocanegra** [comment]
Fixed in https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/629ad8cce3c0ca7ab879dbdc2c971b3ff995e9ae

**Comment by sibwaze** [comment]
Confirm that issue has been fixed, thanks!
