### ISSUE TITLE
`Keep Above Others` window is always selected instead of the currently active window

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-spacer-extended#26]
Initially reported here https://github.com/luisbocanegra/plasma-panel-spacer-extended/issues/8#issuecomment-2068174625

The current approach doesn't grab the active window if there are windows set to be always on top of other windows.

- [x] Select the active window in the current screen (if any)
- [x] Keep track of the last active window on each screen and try to activate that
- [x] If no active window is found activate the top one

**Comment by luisbocanegra** [comment]
Hi again @ShayBox, could you install manually and check if this works as intended now?

**Comment by ShayBox** [comment]
That seems to have fixed that issue, but windows are being grabbed from the center again if you didn't intend for that.

**Comment by luisbocanegra** [comment]
Yeah, haven't tried to tackle that one yet. The only think I guess could be possible is to reposition the window to where the cursor is after the window move is requested, and maybe the drag would continue normally.
