### ISSUE TITLE
Scroll Sensitivity

### ISSUE THREAD

**Issue by PapierFliegr** [luisbocanegra/plasma-panel-spacer-extended#30]
Installed Version: 1.6.1 via "Add Widgets"
Device: Logitech MX Master 3

I am using the Mouse Scroll Action to switch Virtual Desktops.
It seems like the threshold to trigger the action with the mouse is below one notch of the mousewheel.
Thus I often switch two virtual desktops with one Scrollaction.

Feature Request: Manually set the threshold to trigger the WheelUp/WheelDown Action.

**Comment by luisbocanegra** [comment]
It's even crazier with my laptop's touchpad, I can go through all the desktops with a very small movement. Will look into this soon.

**Comment by luisbocanegra** [comment]
https://github.com/luisbocanegra/plasma-panel-spacer-extended/issues/22#issuecomment-2111491453
> Was trying to reproduce the maximized thing and to detect the input device for wheel events (so there can be different thresholds for touchpad and mouse) for https://github.com/luisbocanegra/plasma-panel-spacer-extended/issues/30, but the device was always touchpad even when using mouse wheel. So I decided to try with X11 and the device type does change there (probably Qt6 bug).

Added configuration option to increase the scrolling threshold, it is applied to all devices until the above bug is fixed. Testing with my laptop's touchpad it's not perfect but at least is usable now. Can you please test with your mouse?

**Comment by PapierFliegr** [comment]
Will do on saturday :)

**Comment by PapierFliegr** [comment]
Sorry, for the late reply... forgot to do it...

So the default setting of 120 already improved the scrolling and seems like the perfect value for me, but that's somehow curios.
It looks like 120 is the minimal setting. I tried setting the value to lower than 120 but that was accepted.
For higher values it works as intended.

**Comment by luisbocanegra** [comment]
Minimum is 1 now. Thanks for testing
