### ISSUE TITLE
Dragging window from the panel is broken in X11 session

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-spacer-extended#32]
The window drag just gets stuck somehow, after pressing a key the window teleports to the new cursor position then stays there, also the mouse buttons stop working until `Esc` is pressed which returns everything to normal.

I suspect either X11 doesn't like the [Switch from MouseArea to Handlers](https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/f8f47c3c111208c8bb53d4a0d07b579ecaada2ee), because running the raw command works just fine:

```
sh '/home/luis/.local/share/plasma/plasmoids/luisbocanegra.panelspacer.extended/contents/ui/tools/run_kwin_script.sh' 'focusTopWindow' '/home/luis/.local/share/plasma/plasmoids/luisbocanegra.panelspacer.extended/contents/ui/tools/focusTopWindow.js' true;qdbus6 org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut "Window Move"
```

**Comment by leuchtrakete666** [comment]
would be great if you get this to work. on wayland it does what it should, but i resist to switch until at least one more year or longer, until i can replicate my for years trained x11 workflow on wayland.

i want to copy the latte-dock behaviour with BorderlessMaximizedWindows and drag down from the taskbar.

**Comment by luisbocanegra** [comment]
Hi, I will try to bring back the old method for X11 session but you should know that it is going to be inferior: **Drag + Click to drop** instead of the current **Drag + Release to drop**.

**Comment by leuchtrakete666** [comment]
its working. 

interestingly when when moving from inside the window, lets say i grab the window at the toolbar, the window move is causing no problems. only from grabing the applet.

your solution works well, thank you.

how was latte-dock handling this? with api calls?

**Comment by luisbocanegra** [comment]
> its working.

Nice

> interestingly when when moving from inside the window, lets say i grab the window at the toolbar, the window move is causing no problems. only from grabing the applet.
> how was latte-dock handling this? with api calls?

Yeah that is because I am using the Scripting API to move the window and it currently only drags from the middle. While Latte used C++, though I think in wayland the drag the cursor was locked to the middle of the window too.

From the widget side of things maybe I can take a look again at how latte triggered the drag and port it here, at least for X11

**Comment by leuchtrakete666** [comment]
if you like to tinker, than thanks. but i dont know how much sense it makes to put much effort in this issue. more and more are moving to wayland anyway. i would have preferred to stay on plasma5 for half year longer. but yeah ... rolling distro...
