### ISSUE TITLE
Search for action by typing keywords when action list is opened [FEATURE REQUEST]

### ISSUE THREAD

**Issue by resiehnnes** [luisbocanegra/plasma-panel-spacer-extended#35]
Would be handy to find action by typing a keyword when action list is opened while setting up different actions to different mouse interactions.

**Comment by luisbocanegra** [comment]
Switched from the ugly combobox to a searchable listview in https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/4305e749cf407942cba3d8fc21d6fc5d87f74b67 please try it out and let me know if something could be improved

![Screenshot_20240524_234710](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/15076387/e10c9ecc-6558-4ff5-ab81-715d8a981b59)


To test do one of these:

- Clone and run `./install.sh` (assuming the build dependencies are installed)
- Or clone and run `kpackagetool6 -t Plasma/Applet -u package/` inside the project
- Easiest, download the file below and run `kpackagetool6 -t Plasma/Applet -u plasmoid-spacer-extended-v1.7.1.zip`

[plasmoid-spacer-extended-v1.7.1.zip](https://github.com/luisbocanegra/plasma-panel-spacer-extended/files/15441874/plasmoid-spacer-extended-v1.7.1.zip)

**Comment by resiehnnes** [comment]
@luisbocanegra This is even better than I was expecting, great job! :heart:  I updated your widget the easiest way downloading the zip and gave it a go. Few things that could be improved in my opinion:

1. Make 'listview' collapse (close) after desired action is selected. Clicking on 'edit' icon actually does that, but I think it is more intuitive to let the widget do it for you.
2. This one is a cosmetic one. Make adjustments to horizontal padding in 'Behavior' to fit the content nicely inside the window (see picture below)

![pic](https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/52158526/2c86d860-fc8e-46e4-95b5-e43aa7f34637)

**Comment by luisbocanegra** [comment]
>     1. Make 'listview' collapse (close) after desired action is selected. Clicking on 'edit' icon actually does that, but I think it is more intuitive to let the widget do it for you.

Done

>     2. This one is a cosmetic one. Make adjustments to horizontal padding in 'Behavior' to fit the content nicely inside the window (see picture below)

Should be fixed now

[plasmoid-spacer-extended-v1.7.2.zip](https://github.com/luisbocanegra/plasma-panel-spacer-extended/files/15443470/plasmoid-spacer-extended-v1.7.2.zip)

**Comment by resiehnnes** [comment]
@luisbocanegra Can confirm on both issues, works like a charm now. Thank you for fantastic widget!
