### ISSUE TITLE
[Feature request] Add "Run Command" option for actions

### ISSUE THREAD

**Issue by ghost** [luisbocanegra/plasma-panel-spacer-extended#4]
[Spacer as Pager](https://github.com/eatsu/plasmoid-spacer-as-pager) already did that, but Panel Spacer Extended has more gestures, which is great. Plus:

- It may help to reduce the long actions list and the many variants (as planned in issue #3), and leave the choice to the user.
- Optimally, best of two worlds, have one list of examples of custom commands that the user can copy from, which may be better than a long list for each gesture.

**Comment by luisbocanegra** [comment]
Sounds like a good plan. I was experimenting populating the drop-down with all the detected shortcuts and it went ridiculously big and wide lol. will look into other way of displaying them and allowing custom commands.

**Comment by luisbocanegra** [comment]
Also :eyes: after looking for a bit in [Spacer as Pager](https://github.com/eatsu/plasmoid-spacer-as-pager) I realized there is no need to have compiled code at all! :sob:
