### ISSUE TITLE
Action: Move Window to Next Activity

### ISSUE THREAD

**Issue by mysteryx93** [luisbocanegra/plasma-panel-spacer-extended#42]
Instead of using multiple Desktops, I'm using 2 Activities and switch between them with Meta+Tab.

It would be great to have action: Move Window to Next Activity and Move Window to Previous Activity.

**Comment by luisbocanegra** [comment]
I will try to make a kwin script that does this, then expose a shortcut so this widget shows it.

**Comment by luisbocanegra** [comment]
Hi, @mysteryx93 I uploaded the KWin script here https://github.com/luisbocanegra/kwin-window-activity-switcher can you try it out?

**Comment by mysteryx93** [comment]
Seems to be working just fine!

**Comment by luisbocanegra** [comment]
Thank you for testing.
