### ISSUE TITLE
Cannot remove actions anymore

### ISSUE THREAD

**Issue by ShayBox** [luisbocanegra/plasma-panel-spacer-extended#48]
I cannot remove actions anymore, but I'm using the same version (1.8.3) as the last time, and I was able to, maybe a KDE update broke it?

![image](https://github.com/user-attachments/assets/ca1d0b0a-3866-4dab-b165-807fc12eb8bc)

**Comment by luisbocanegra** [comment]
Yeah just noticed this yesterday (thanks to https://github.com/luisbocanegra/plasma-panel-spacer-extended/pull/46) it has been fixed in https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/17502971d4bb61b6634f6e88f3c8bfd01ac1efbd and an uptate will be released later today/tomorrow

**Comment by luisbocanegra** [comment]
Fixed in https://github.com/luisbocanegra/plasma-panel-spacer-extended/releases/tag/v1.9.0
