### ISSUE TITLE
Drag the top window on current screen, not the active window.

### ISSUE THREAD

**Issue by developer91234** [luisbocanegra/plasma-panel-spacer-extended#8]
This is a behavior of latte dock. KDE's new global menu widget also only shows the menu for the active window for the current display, not the menu for the active window on some other display. So tracking by display should in theory be doable.

**Comment by luisbocanegra** [comment]
Currently, the widget uses `qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut "Window Move"` to start the dragging, unfortunately there is no separate shortcut to drag the window only if is in the current screen.

Someone will have to take a look at what Latte does and try porting that here if possible.

**Comment by luisbocanegra** [comment]
Found a way do do this, with a KWin Script **(Plasma 6 only)**. Please ignore the lag, looks like recording two monitors was too much for my IGPU 😆

https://github.com/luisbocanegra/plasma-panel-spacer-extended/assets/15076387/975cb051-c66d-4cec-8fab-4a57b1fe1d96

1. It checks where the mouse is and uses that to set the active screen
2. Loops through the windows and checks they are in the active screen not minimized and other properties
3. Then we get the window that is higher in the stack and activate it
4. Finally send the window action and it runs on that window

This will also benefit all other kwin shortcuts that do things with the active window :partying_face: 

It's not yet integrated with the widget code but you can be tested by running a script with the following (update the SCRIPT path):

`move-window.sh`

```sh
#!/bin/env bash

# load the script
echo "running"
SCRIPT="/home/luis/projects/plasma-panel-spacer-extended/moveTopWindow.js"
SCRIPT_NAME="moveTopWindow"
qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting.unloadScript "$SCRIPT_NAME"
script_id=$(qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting.loadScript "${SCRIPT}" "$SCRIPT_NAME")

# run
qdbus org.kde.KWin /Scripting/Script"$script_id" org.kde.kwin.Script.run
sleep 1
qdbus org.kde.KWin /Scripting/Script"$script_id" org.kde.kwin.Script.stop
```

`moveTopWindow.js`

```js
const windows = workspace.windowList();
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@\n");
var windowToMove
let stackOrder = -1

var currentScreen = workspace.screenAt(workspace.cursorPos)
for (var i = 0; i < windows.length; i++) {
  if (windows[i].output === currentScreen && !windows[i].desktopWindow && windows[i].normalWindow && !windows[i].minimized && windows[i].moveable && !windows[i].hidden) {
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@\n");
    print(windows[i].caption);
    print(windows[i].resourceName);
    print(windows[i].resourceClass);
    print(windows[i].stackingOrder);
    if (windows[i].stackingOrder > stackOrder) {
      windowToMove = windows[i]
    }
    stackOrder = windows[i].stackingOrder
  }
}
resut = ("Dragging: " + windowToMove.caption + "|" + windowToMove.resourceName + "|" + windowToMove.resourceClass + "|" + windowToMove.stackingOrder + "|" + windowToMove.output.name)
print("MOVE")
print(resut)
workspace.activeWindow = windowToMove
workspace.slotWindowMove()
callDBus("org.kde.plasmashell", "/org/kde/osdService", "org.kde.osdService", "showText", "window", resut);
```

**Comment by ShayBox** [comment]
Any ETA on this being merged? since #19 has been fixed, this and #18 are the only things I need to completely replace LatteDock and have a working top-bar again.

**Comment by luisbocanegra** [comment]
Will publish a release with #19 tomorrow.

For dragging the top window I have a working version already, just need to also activate the top window for all the other shortcuts that need it (e.g. close window and many others)

**Comment by luisbocanegra** [comment]
This should now work on main too with the following shortcuts:
- **kwin** ExposeClass
- **kwin** Decrease Opacity
- **kwin** Increase Opacity
- **kwin** InvertWindow
- **kwin** Kill Window
- **kwin** Setup Window Shortcut
- **kwin** Switch Window Down
- **kwin** Switch Window Left
- **kwin** Switch Window Right
- **kwin** Switch Window Up
- **kwin** Toggle Window Raise/Lower
- **kwin** Walk Through Windows of Current Application
- **kwin** Window Above Other Windows
- **kwin** Window Below Other Windows
- **kwin** Window Close
- **kwin** Window Fullscreen
- **kwin** Window Grow
- **kwin** Window Lower
- **kwin** Window Maximize
- **kwin** Window Minimize
- **kwin** Window Move
- **kwin** Window No Border
- **kwin** Window On All Desktops
- **kwin** Window One Desktop
- **kwin** Window One Screen
- **kwin** Window Operations Menu
- **kwin** Window Pack
- **kwin** Window Quick Tile
- **kwin** Window Raise
- **kwin** Window Resize
- **kwin** Window Shade
- **kwin** Window Shrink
- **kwin** Window to

**Comment by luisbocanegra** [comment]
Available on https://github.com/luisbocanegra/plasma-panel-spacer-extended/releases/tag/v1.6.0

**Comment by ShayBox** [comment]
One issue with this approach is that if you have a window pinned to top, it will always grab that window. I'm not sure this can be solved with a script only plasmoid though, it would have to involve writing C++ code.

**Comment by luisbocanegra** [comment]
Hmmm maybe I could:

1. Keep track of the last active window on each screen and try to activate that
2. If the last window is no longer there look for another active window
3. If that doesn't exist either then grab the top one
